name = "mf-corses"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

build = { command = "npm run build", cwd = "./", watch_paths = ["src/**/*.ts"] }
main = "dist/mf_corses/browser/main.js"